### ISSUE TITLE
Python2.7 incompatible with pfSense 2.4.5

### ISSUE THREAD

**Issue by kinther** [pfsensible/core#13]
In pfSense 2.4.5 it appears that support for Python2.7 is no longer there.  In /usr/local/bin/python3.7 is all that is there.

[2.4.5-RELEASE][admin@pfsense-test]/root: ls /usr/local/bin/python*
/usr/local/bin/python3.7         /usr/local/bin/python3.7-config  /usr/local/bin/python3.7m        /usr/local/bin/python3.7m-config

Running a playbook per the normal method to add an alias fails on new 2.4.5 pfSense:

TASK [Add test alias] ***************************************************************************************************************************************
task path: /home/kinther/test2.yml:11
<172.16.0.10> ESTABLISH PARAMIKO SSH CONNECTION FOR USER: ansibleuser on PORT 22 TO 172.16.0.10
<172.16.0.10> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1587500186.5604308-239104599291623 `" && echo ansible-tmp-1587500186.5604308-239104599291623="` echo /tmp/ansible-tmp-1587500186.5604308-239104599291623 `" ) && sleep 0'
Using module file /home/kinther/.ansible/collections/ansible_collections/pfsensible/core/plugins/modules/alias.py
<172.16.0.10> PUT /home/kinther/.ansible/tmp/ansible-local-42188btu0sfj3/tmppljgqbz8 TO /tmp/ansible-tmp-1587500186.5604308-239104599291623/AnsiballZ_alias.py
<172.16.0.10> EXEC /bin/sh -c 'chmod u+x /tmp/ansible-tmp-1587500186.5604308-239104599291623/ /tmp/ansible-tmp-1587500186.5604308-239104599291623/AnsiballZ_alias.py && sleep 0'
<172.16.0.10> EXEC /bin/sh -c '/usr/local/bin/python2.7 /tmp/ansible-tmp-1587500186.5604308-239104599291623/AnsiballZ_alias.py && sleep 0'
<172.16.0.10> EXEC /bin/sh -c 'rm -f -r /tmp/ansible-tmp-1587500186.5604308-239104599291623/ > /dev/null 2>&1 && sleep 0'
fatal: [pfsense-test]: FAILED! => {
    "changed": false,
    "module_stderr": "",
    "module_stdout": "/bin/sh: /usr/local/bin/python2.7: not found\r\n",
    "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
    "rc": 127
}

Environment information:

(testenv) [kinther@server ~]$ ansible --version
ansible 2.9.6
  config file = /home/kinther/ansible.cfg
  configured module search path = ['/home/kinther/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kinther/testenv/lib64/python3.6/site-packages/ansible
  executable location = /home/kinther/testenv/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

**Comment by kinther** [comment]
If I remove the environmental variable declaring python2.7 should be used, there is a Traceback from python3.7 as it is the discovered python interpreter:

The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Cross-device link: '/tmp/tmpicb_vu7j' -> '/cf/conf/config.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ansible-tmp-1587500505.7012663-243551933932195/AnsiballZ_alias.py", line 102, in <module>
    _ansiballz_main()
  File "/tmp/ansible-tmp-1587500505.7012663-243551933932195/AnsiballZ_alias.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/ansible-tmp-1587500505.7012663-243551933932195/AnsiballZ_alias.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.pfsensible.core.plugins.modules.alias', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_pfsensible.core.alias_payload_waa18r4a/ansible_pfsensible.core.alias_payload.zip/ansible_collections/pfsensible/core/plugins/modules/alias.py", line 99, in <module>
  File "/tmp/ansible_pfsensible.core.alias_payload_waa18r4a/ansible_pfsensible.core.alias_payload.zip/ansible_collections/pfsensible/core/plugins/modules/alias.py", line 95, in main
  File "/tmp/ansible_pfsensible.core.alias_payload_waa18r4a/ansible_pfsensible.core.alias_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/module_base.py", line 150, in commit_changes
  File "/tmp/ansible_pfsensible.core.alias_payload_waa18r4a/ansible_pfsensible.core.alias_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/pfsense.py", line 537, in write_config
  File "/usr/local/lib/python3.7/shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "/usr/local/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/cf/conf/config.xml'

**Comment by f-bor** [comment]
Hi,

This is not really related to us. You just have to adapt ansible_python_interpreter parameter for this host to use python 3.7.

**Comment by kinther** [comment]
I suppose I was simply noting that in its current form this collection points to python2.7 in the README file, but it appears going forward that version is no longer supported.  Might be a good thing to reference that there is a slight change between 2.4.4 and 2.4.5 in that respect.

**Comment by f-bor** [comment]
Thanks for reporting this. I have added a note for python 3.7.

**Comment by opoplawski** [comment]
It may also be worth noting that with ansible's current python autodetection, setting `ansible_python_interpreter` seems unnecessary.
