### ISSUE TITLE
pfsense_interface module cannot remove a subinterface

### ISSUE THREAD

**Issue by MCH-JO** [pfsensible/core#35]
>Hello
I have just noticed that you have a second repo for this collection.  
But I have already written an issue on it: [issue](https://github.com/opoplawski/ansible-pfsense/issues/90)  
So I post It here, tell me which one you want me to remove.

Hello,

First, thank you for the plugins.

I'm encountering a problem when i'm tring to use the **pfsense_interface** module to delete an existing and empty of any rule or separator interface.  
It throws me this -vvv error message:  

```bash
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1654160293.51-1420-237622735159209/AnsiballZ_pfsense_interface.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1654160293.51-1420-237622735159209/AnsiballZ_pfsense_interface.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1654160293.51-1420-237622735159209/AnsiballZ_pfsense_interface.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.pfsensible.core.plugins.modules.pfsense_interface', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_pfsensible.core.pfsense_interface_payload_99eqtdqt/ansible_pfsensible.core.pfsense_interface_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_interface.py", line 152, in <module>
  File "/tmp/ansible_pfsensible.core.pfsense_interface_payload_99eqtdqt/ansible_pfsensible.core.pfsense_interface_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_interface.py", line 147, in main
  File "/tmp/ansible_pfsensible.core.pfsense_interface_payload_99eqtdqt/ansible_pfsensible.core.pfsense_interface_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/module_base.py", line 228, in run
  File "/tmp/ansible_pfsensible.core.pfsense_interface_payload_99eqtdqt/ansible_pfsensible.core.pfsense_interface_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/module_base.py", line 204, in _remove
  File "/tmp/ansible_pfsensible.core.pfsense_interface_payload_99eqtdqt/ansible_pfsensible.core.pfsense_interface_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/interface.py", line 316, in _pre_remove_target_elt
  File "/tmp/ansible_pfsensible.core.pfsense_interface_payload_99eqtdqt/ansible_pfsensible.core.pfsense_interface_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/interface.py", line 365, in _remove_all_separators

TypeError: 'NoneType' object is not iterable
fatal: [pfsense]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 192.168.200.254 closed.\r
",
    "module_stdout": "Traceback (most recent call last):\r
  File \"/root/.ansible/tmp/ansible-tmp-1654160293.51-1420-237622735159209/AnsiballZ_pfsense_interface.py\", line 102, in <module>\r
    _ansiballz_main()\r
  File \"/root/.ansible/tmp/ansible-tmp-1654160293.51-1420-237622735159209/AnsiballZ_pfsense_interface.py\", line 94, in _ansiballz_main\r
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r
  File \"/root/.ansible/tmp/ansible-tmp-1654160293.51-1420-237622735159209/AnsiballZ_pfsense_interface.py\", line 40, in invoke_module\r
    runpy.run_module(mod_name='ansible_collections.pfsensible.core.plugins.modules.pfsense_interface', init_globals=None, run_name='__main__', alter_sys=True)\r
  File \"/usr/local/lib/python3.8/runpy.py\", line 207, in run_module\r
    return _run_module_code(code, init_globals, run_name, mod_spec)\r
  File \"/usr/local/lib/python3.8/runpy.py\", line 97, in _run_module_code\r
    _run_code(code, mod_globals, init_globals,\r
  File \"/usr/local/lib/python3.8/runpy.py\", line 87, in _run_code\r
    exec(code, run_globals)\r
  File \"/tmp/ansible_pfsensible.core.pfsense_interface_payload_99eqtdqt/ansible_pfsensible.core.pfsense_interface_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_interface.py\", line 152, in <module>\r
  File \"/tmp/ansible_pfsensible.core.pfsense_interface_payload_99eqtdqt/ansible_pfsensible.core.pfsense_interface_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_interface.py\", line 147, in main\r
  File \"/tmp/ansible_pfsensible.core.pfsense_interface_payload_99eqtdqt/ansible_pfsensible.core.pfsense_interface_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/module_base.py\", line 228, in run\r
  File \"/tmp/ansible_pfsensible.core.pfsense_interface_payload_99eqtdqt/ansible_pfsensible.core.pfsense_interface_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/module_base.py\", line 204, in _remove\r
  File \"/tmp/ansible_pfsensible.core.pfsense_interface_payload_99eqtdqt/ansible_pfsensible.core.pfsense_interface_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/interface.py\", line 316, in _pre_remove_target_elt\r
  File \"/tmp/ansible_pfsensible.core.pfsense_interface_payload_99eqtdqt/ansible_pfsensible.core.pfsense_interface_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/interface.py\", line 365, in _remove_all_separators\r
TypeError: 'NoneType' object is not iterable\r
",
    "msg": "MODULE FAILURE
See stdout/stderr for the exact error",
    "rc": 1
}
```

## Versions

My pfSense is in a virtualbox VM  
Virtualbox version: 6.1.34  
Ansible version: 2.9.27  
pfSense version: 2.6.0  

## Description

I'm trying to automate the creation of subinterfaces on my pfSense install using Ansible.  
I have a task that first creates a VLAN.  
Then another tasks that create the associated subinterface without any separator neither any rule.  
Finally, a third task to remove the subinterface (in order to remove the VLAN next) and I face a problem: Ansible throws me the error above.  

## Steps to reproduce

1. Create a pfSense VM using virtualbox  

2. Run the following Ansible playbook  

```yaml
---
- name: "VLANs and subinterfaces configuration on pfSense firewall"
  hosts: 'pfsense'
  become: true
  collections:
    - 'pfsensible.core'
  tasks:
    - name: "Create a VLAN"
      pfsensible.core.pfsense_vlan:
        interface: 'em1'
        vlan_id: '111'
        descr: '111_VLAN'
        state: 'present'

    - name: "Create subinterface"
      pfsensible.core.pfsense_interface:
        interface: 'em1.111'
        descr: '111_VLAN'
        enable: true
        ipv4_type: 'static'
        ipv4_address: '192.168.66.1'
        ipv4_prefixlen: 24
        state: 'present'

    - name: "Remove subinterface"
      pfsensible.core.pfsense_interface:
        interface: 'em1.111'
        descr: '111_VLAN'
        enable: true
        ipv4_type: 'static'
        ipv4_address: '192.168.66.1'
        ipv4_prefixlen: 24
        state: 'absent'
```

## Hypothesis

The problem seems to comes from the fact that the subinterface that I'm trying to remove doesn't have any separators in its rules.

It looks like a bug in the `module_utils/network/pfsense/interface.py` file, at line [368](https://github.com/opoplawski/ansible-pfsense/blob/71f92e0773abca9aa7ec7053b6b568fa378f37bd/module_utils/network/pfsense/interface.py#L368). I'm not very familiar with Python but it looks like there's no check to verify that the variable `separator` is not empty before trying to iterate on it in the for loop.

## Workaround

In Ansible, just before the task that deletes the subinterface, you can add a task to create a dummy separator associated to the subinterface rules and after that the task that removes the subinterface works, like so:

```yaml
- name: "VLANs and subinterfaces configuration on pfSense firewall"
  hosts: 'pfsense'
  become: true
  collections:
    - 'pfsensible.core'
  tasks:
    - name: "Create a VLAN"
      pfsensible.core.pfsense_vlan:
        interface: 'em1'
        vlan_id: '111'
        descr: '111_VLAN'
        state: 'present'

    - name: "Create subinterface"
      pfsensible.core.pfsense_interface:
        interface: 'em1.111'
        descr: '111_VLAN'
        enable: true
        ipv4_type: 'static'
        ipv4_address: '192.168.66.1'
        ipv4_prefixlen: 24
        state: 'present'

    - name: "Workaround removing interface problem"
      block:
        - name: "Add dummy separator to subinterface rules"
          pfsensible.core.pfsense_rule_separator:
            color: 'info'
            interface: '111_VLAN'
            name: 'Dummy separator'
            state: 'present'

        - name: "Remove subinterface"
          pfsensible.core.pfsense_interface:
            interface: 'em1.111'
            descr: '111_VLAN'
            enable: true
            ipv4_type: 'static'
            ipv4_address: '192.168.66.1'
            ipv4_prefixlen: 24
            state: 'absent'
```

## Proposed fix

I modified the function `_remove_all_separators` like so:

```python
def _remove_all_separators(self, interface):
    """ delete all interface separators """
    todel = []
    separators = self.pfsense.rules.find('separator')
    if separators is not None:
        for interface_elt in separators:
            if interface_elt.tag != interface:
                continue
            for separator_elt in interface_elt:
                todel.append(separator_elt)
            for separator_elt in todel:
                cmd = 'delete rule_separator \'{0}\', interface=\'{1}\''.format(separator_elt.find('text').text, interface)
                self.result['commands'].append(cmd)
                interface_elt.remove(separator_elt)
            separators.remove(interface_elt)
            break
```

And ran the problematic Ansible code and it worked, the subinterface was deleted successfuly without errors. I'm not sure if this is the right way to fix it but let me know if you want me to open a PR.

Thanks for the help

Jo

**Comment by opoplawski** [comment]
I can't reproduce this with current master, so I'm hoping it's fixed.  Could you give it a try?

**Comment by opoplawski** [comment]
I'm considering this fixed.  Feel free to re-open if needed.

**Comment by Doc-Tiebeau** [comment]
This bug is still present in pfesensible.core v0.5.3

I experienced it when I try to remove the generic LAN interface just after deployment.

Ansible version: 2.14.8
pfSense version: 2.7.0

The workaround with dummy separator work's fine in my case.

You can reopen this issue.
