### ISSUE TITLE
Interface groups cannot be created, but only changed

### ISSUE THREAD

**Issue by lolllpop** [pfsensible/core#74]
Hi all,

I tried to manage my interface groups with pfsensible. The simple ansible task below can change the members of an existing interface group (i.e. there's already a group with the same name in the config.xml). Creating a new interface group with a new name, however, results in following error: IndexError: list index out of range

```
- name: Add interface group
  pfsensible.core.pfsense_interface_group:
    name: SRV
    members:
      - 121_SRV_PRD
      - 123_SRV_DEV
```

```
TASK [pfs_base : Add interface group] ******************************************************************************************************************************************************************************************************
task path: /home/user/ansible/roles/pfs_base/tasks/main.yml:27
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 107, in <module>
  File "<stdin>", line 99, in _ansiballz_main
  File "<stdin>", line 47, in invoke_module
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_pfsensible.core.pfsense_interface_group_payload_wgh2n3j9/ansible_pfsensible.core.pfsense_interface_group_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_interface_group.py", line 93, in <module>
  File "/tmp/ansible_pfsensible.core.pfsense_interface_group_payload_wgh2n3j9/ansible_pfsensible.core.pfsense_interface_group_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_interface_group.py", line 88, in main
  File "/tmp/ansible_pfsensible.core.pfsense_interface_group_payload_wgh2n3j9/ansible_pfsensible.core.pfsense_interface_group_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/module_base.py", line 227, in run
  File "/tmp/ansible_pfsensible.core.pfsense_interface_group_payload_wgh2n3j9/ansible_pfsensible.core.pfsense_interface_group_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/interface_group.py", line 113, in _find_target
IndexError: list index out of range
fatal: [versefw]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 107, in <module>\n  File \"<stdin>\", line 99, in _ansiballz_main\n  File \"<stdin>\", line 47, in invoke_module\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_pfsensible.core.pfsense_interface_group_payload_wgh2n3j9/ansible_pfsensible.core.pfsense_interface_group_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_interface_group.py\", line 93, in <module>\n  File \"/tmp/ansible_pfsensible.core.pfsense_interface_group_payload_wgh2n3j9/ansible_pfsensible.core.pfsense_interface_group_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_interface_group.py\", line 88, in main\n  File \"/tmp/ansible_pfsensible.core.pfsense_interface_group_payload_wgh2n3j9/ansible_pfsensible.core.pfsense_interface_group_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/module_base.py\", line 227, in run\n  File \"/tmp/ansible_pfsensible.core.pfsense_interface_group_payload_wgh2n3j9/ansible_pfsensible.core.pfsense_interface_group_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/interface_group.py\", line 113, in _find_target\nIndexError: list index out of range\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

Using:
ansible [core 2.14.5]
python version = 3.11.3 (main, Jun  9 2023, 16:40:48) [GCC 12.2.1 20230428] (/usr/bin/python3.11)
pfsensible.core   0.5.3

Many thanks for this project!

**Comment by loictlpk** [comment]
I've the same issue... Hope dev will resolve this problem
